### ISSUE TITLE
Ripping sprites and textures from Lego Mario/Luigi/Peach

### ISSUE THREAD

**Issue by ghost** [jonyo/mario-lego#28]
Not an issue, but yes a request: being able to extract sprites/textures that are only visible/usable on their chest, like flag animation among others.

I know the app has similar sprites, but are not equal and they aren't animated as they show up in the toy itself.

Thanks.

**Comment by jonyo** [comment]
If I'm understanding you correctly, it sounds a little beyond the scope of this project.

The project is just a barcode generator.  No ripping or de-compiling or anything like that.  Others figured out "how the barcodes work" and published how they work online.  I took that and used it to create a PHP script that lets you generate codes with different options like # on a page and things like that.

**Comment by ghost** [comment]
Alright, understood.

If, somehow, you find a way or know about a tool which can do what i asked here, lemme know.

Thanks!
